# This file is NOT recommended to be changed manually
# Intended as a dashboard to see what settings are in effect at any given time
#
# Recommended usage:
#   - Use commands to update settings (/character, /imgmodel, /imgtags, etc)
#   - Behavior and State should be defined per character (see example char 'M1nty')
#   - Extension settings can also be set per character.
#   - Check out the dict_.yaml files to adjust settings presets.

behavior:
  chance_to_reply_to_other_bots: 0.0
  conversation_recency: 600
  go_wild_in_channel: true
  ignore_history: false
  ignore_parentheses: true
  only_speak_when_spoken_to: true
  reply_to_bots_when_addressed: 0.0
  reply_to_itself: 0.0
  reply_with_image: 0.0
  time_offset: 0.0
imgtag:
  imgtag_name: ''
  negative_prompt_prefix: ''
  positive_prompt_prefix: ''
  positive_prompt_suffix: ''
  positive_prompt_suffix2: ''
  positive_prompt_suffix2_blacklist: ''
  presets:
imgmodel:
  imgmodel_name: ''
  imgmodel_url: ''
  override_settings:
    CLIP_stop_at_last_layers: 1
    sd_model_checkpoint: ''
    sd_vae: Automatic
  payload:
    restore_faces: False
    sampler_name: "DPM++ 2M Karras"
    steps: 30
    cfg_scale: 7
    height: 896
    width: 1152
    enable_hr: False
    hr_upscaler: "Latent"
    denoising_strength: 0.5
    hr_scale: 2
llmcontext:
  bot_description: Friendly AI assistant
  bot_emoji: "\xF0\u0178\u0178\xA3"
  context: |
    The following is a conversation with an AI Large Language Model. The AI has been trained to answer questions, provide recommendations, and help with decision making. The AI follows user requests. The AI thinks outside the box.
  greeting: How can I help you today?
  name: AI
llmstate:
  state:
    preset: ''
    grammar: ''
    max_new_tokens: 512
    do_sample: true
    temperature: 0.7
    top_p: 0.9
    typical_p: 1
    min_p: 0.1
    repetition_penalty: 1.3
    encoder_repetition_penalty: 1.0
    repetition_penalty_range: 30
    top_k: 0
    min_length: 0
    no_repeat_ngram_size: 0
    num_beams: 1
    penalty_alpha: 0
    length_penalty: 1
    early_stopping: false
    add_bos_token: false
    skip_special_tokens: true